let producten = [
    { "eten1" : "diepvriesfriet",
    "foto1" :  "img/diepvriesfriet.png",
    "uitstoot1" : "6,153",
    "keuze1" : "goedrechts",
    "eten2" : "krieltjes",
    "foto2" :  "img/krieltjes.png",
    "uitstoot2" : "0,923",
    "keuze2" : "foutrechts"
    },
    { "eten1" : "bier",
    "foto1" :  "img/bier.png",
    "keuze1" : "foutlinks",
    "uitstoot1" : "0,707",
    "eten2" : "wijn",
    "foto2" :  "img/wijn.png",
    "uitstoot2" : "2,277", 
    "keuze2" : "goedlinks"
    },
    { "eten1" : "aardbeien",
    "foto1" :  "img/aardbei.png",
    "uitstoot1" : "6,412",
    "keuze1" : "goedrechts",
    "eten2" : "manderijnen",
    "foto2" :  "img/manderijnen.png",
    "uitstoot2" : "0,865",
    "keuze2" : "foutrechts"
    },
    { "eten1" : "pindakaas",
    "foto1" : "img/pindakaas.png",
    "uitstoot1" : "8,678",
    "keuze1" : "goedrechts",
    "eten2" : "melk hagelslag",
    "foto2" : "img/melk hagelslag.png",
    "uitstoot2" : "3,239",
    "keuze2" : "foutrechts"
    },
    { "eten1" : "chips",
    "foto1" : "img/chips.png",
    "uitstoot1" : "4,833",
    "keuze1" : "goedrechts",
    "eten2" : "popcorn",
    "foto2" : "img/popcorn.png",
    "uitstoot2" : "0,950",
    "keuze2" : "foutrechts"
    },
    { "eten1" : "pinda's",
    "foto1" : "img/pindas.png",
    "uitstoot1" : "7,355",
    "keuze1" : "goedrechts",
    "eten2" : "pistachnoten",
    "foto2" : "img/pistache noten.png",
    "uitstoot2" : "3,993",
    "keuze2" : "foutrechts"
    },
    { "eten1" : "olijfolie",
    "foto1" : "img/olijfollie.png",
    "uitstoot1" : "7,172",
    "keuze1" : "goedrechts",
    "eten2" : "zonnebloemolie",
    "foto2" : "img/zonnebloemolie.png",
    "uitstoot2" : "5,011",
    "keuze2" : "foutrechts"
    },
    { "eten1" : "half-om-half gehakt",
    "foto1" : "img/half om half gehakt.png",
    "uitstoot1" : "20,373",
    "keuze1" : "foutlinks",
    "eten2" : "runder gehakt",
    "foto2" : "img/rundergehakt.png",
    "uitstoot2" : "30,026",
    "keuze2" : "goedlinks"
    },
    { "eten1" : "kipfilet",
    "foto1" : "img/kipfilet.png",
    "uitstoot1" : "10,873",
    "keuze1" : "foutlinks",
    "eten2" : "kipdrumsticks",
    "foto2" : "img/drumsticks.png",
    "uitstoot2" : "13,550",
    "keuze2" : "goedlinks"
    },
    { "eten1" : "schouderham",
    "foto1" : "img/schouderham.png",
    "uitstoot1" : "10,824",
    "keuze1" : "goedrechts",
    "eten2" : "smeerleverworst",
    "foto2" : "img/smeerleverworst.png",
    "uitstoot2" : "5,732",
    "keuze2" : "foutrechts"
    }
];